version: "3.9"
services:
  server:
    image: bazel/server:server.container
    ports:
      - "8980:8980"
    privileged: true
  worker:
    image: bazel/worker:worker.container
    depends_on:
      - "server"
    privileged: true