version: "3.9"
services:
  server:
    image: bazel/server:server.container
    ports:
      - "8980:8980"
    environment:
      - USER=areddy
  worker:
    image: bazel/worker:worker.container
    environment:
      - USER=areddy