version: "3.9"
services:

  sandbox:
    build: "./test"
    volumes:
      - "./test:/var/lib"
    command: tail -f /dev/null
  
  cache:
    image: redis:5.0.9
    ports:
      - "6379:6379"
  
  server:
    image: bazelbuild/buildfarm-server:latest
    command:
      - "/var/lib/buildfarm-server/shard-server.config.example"
    ports:
      - "8980:8980"
    depends_on:
      - "cache"
    volumes:
      - ./config:/var/lib/buildfarm-server
    privileged: true
  
  worker:
    image: bazelbuild/buildfarm-worker:latest
    command:
      - "/var/lib/buildfarm-shard-worker/shard-worker.config.example"
      - "--public_name=worker:8981"
    depends_on: 
      - "cache"
    volumes:
      - "/tmp/worker:/tmp/worker"
      - "./config:/var/lib/buildfarm-shard-worker"
    ports:
      - "8981:8981"
